apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
bases:
  - ../../base
resources:
  - namespace.yaml
  - dragonfly.yaml # Dragonfly для prod (2 репліки)
  - hpa.yaml       # Horizontal Pod Autoscaler
patches:
- target:
    kind: Deployment
    name: course-app
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
