namespace: development
resources:
- ../../base
- namespace.yaml
- dragonfly.yaml
patches:
- target:
    kind: Deployment
    name: course-app
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
